### PyTorch Basic Operation

Sources are from PyTorch website: 
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [13]:
from __future__ import print_function
import torch

In [3]:
# Construct a random initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.1626, 0.9955, 0.6352],
        [0.1317, 0.4534, 0.1702],
        [0.4217, 0.9209, 0.7331],
        [0.1997, 0.0544, 0.8152],
        [0.6405, 0.3840, 0.6557]])


In [4]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [5]:
# Construct a matrix filled zeros and of dtype long
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [7]:
x = x.new_ones(5,3, dtype=torch.double)   #new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtype!
print(x)                                   # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2475, -0.4011,  0.8408],
        [ 0.1580, -0.2158, -1.6077],
        [-0.7198, -0.4919, -2.0045],
        [-1.5156,  0.6089, -0.3042],
        [ 1.0105,  0.1944,  0.4554]])


In [8]:
# Get its size
print(x.size())

torch.Size([5, 3])


**Note**: ```torch.Size``` is in fact a tuple, so it supports all tuple operations.

## Operations

In [9]:
y = torch.rand(5,3)

# add
print(x + y)
print(torch.add(x, y))

result = torch.empty(5,3)  # providing an output tensor as argument
torch.add(x, y, out=result)
print(result)

y.add_(x)                  #  in-place
print(y)

tensor([[ 0.7544,  0.5273,  1.0990],
        [ 0.6674,  0.1656, -1.5419],
        [-0.2497, -0.2469, -1.7595],
        [-1.1562,  0.7213,  0.0902],
        [ 1.9246,  0.9064,  1.2582]])
tensor([[ 0.7544,  0.5273,  1.0990],
        [ 0.6674,  0.1656, -1.5419],
        [-0.2497, -0.2469, -1.7595],
        [-1.1562,  0.7213,  0.0902],
        [ 1.9246,  0.9064,  1.2582]])
tensor([[ 0.7544,  0.5273,  1.0990],
        [ 0.6674,  0.1656, -1.5419],
        [-0.2497, -0.2469, -1.7595],
        [-1.1562,  0.7213,  0.0902],
        [ 1.9246,  0.9064,  1.2582]])
tensor([[ 0.7544,  0.5273,  1.0990],
        [ 0.6674,  0.1656, -1.5419],
        [-0.2497, -0.2469, -1.7595],
        [-1.1562,  0.7213,  0.0902],
        [ 1.9246,  0.9064,  1.2582]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an ```_```. For example: ```x.copy_(y)```, ```x.t_()```, will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [10]:
print(x[:,1])

tensor([-0.4011, -0.2158, -0.4919,  0.6089,  0.1944])


In [11]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
# If you have a one element tensor, 
# use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.5039])
-1.503895998


## Numpy Bridge ##
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and **changing one will change the other**.

In [14]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print("original a:")
print(a)

b = a.numpy()
print("original b:")
print(b)

a.add_(1)
print("changed a and b:")
print(a)
print(b)

original a:
tensor([1., 1., 1., 1., 1.])
original b:
[1. 1. 1. 1. 1.]
changed a and b:
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [15]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA TENSORS ##
Tensors can be moved onto any device using the ```.to``` method.

```
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

```

expected output:
```
tensor([2.9218], device='cuda:0')
tensor([2.9218], dtype=torch.float64)
```